name: ddsp-are
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.1
  - torchaudio>=2.1
  - torchvision
  - pytorch-cuda=12.1
  - numpy>=1.24
  - scipy>=1.11
  - matplotlib>=3.7
  - tqdm>=4.65
  - soundfile>=0.12
  - librosa=0.11.0
  - pip
  - pip:
      - auraloss
      - aquatk==0.1.0
      - mel-cepstral-distance==0.0.4
